project_name: g2
builds:
  -
    id: "g2"
    binary: "g2"
    dir: cmd/g2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
        - apk
        - deb
        - rpm
        - termux.deb
        - archlinux
    release: "1"
    section: default
    priority: extra
