version: 2
project_name: g2
builds:
  -
    id: "g2"
    binary: "g2"
    dir: cmd/g2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
        goarm: "6"
      - goos: windows
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
archives:
  -
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
        - apk
        - deb
        - rpm
        - termux.deb
        - archlinux
    release: "1"
    section: default
    priority: extra
homebrew_casks:
  -
    name: g2
    repository:
      owner: arran4
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}" # From Secrets.TAP_GITHUB_TOKEN update ci.yaml too to match
      pull_request:
        enabled: true
        draft: false
    directory: Formula
